#!/bin/bash
set -ex

if [[ $(hostname) == "void" ]]; then
	echo "Welcome to the void!"

	source_dir=void-linux/
	xargs <$source_dir/packages xbps-install --yes
else
	echo "System not recognized or not supported"
fi
